apiVersion: apps/v1
kind: Deployment
metadata:
  name: yogaclass
  labels:
    app: yogaclass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yogaclass
  template:
    metadata:
      labels:
        app: yogaclass
    spec:
      containers:
        - name: yogaclass
          image: "username/yogaclass:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
