apiVersion: apps/v1
kind: Deployment
metadata:
  name: yogaclass
  labels:
    app: yogaclass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yogaclass
  template:
    metadata:
      labels:
        app: yogaclass
    spec:
      containers:
      - name: yogaclass
        image: "user05.azurecr.io/yogaclass:v1"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/mnt/data"
          name: volume
        readinessProbe:
          httpGet:
            path: '/actuator/health'
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: '/actuator/health'
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 5
        env:
        - name: PROFILE
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: key1
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azurefile
